### ISSUE TITLE
ECM: emotional conversation  generation with internal and external memory issue

### ISSUE THREAD

**Issue by CCYChongyanChen** [xwzhong/papernote#1]
第一点中原文写的emotion embedding应该是real-valued, low dimension 的,你写成了高维？它用大连理工的情感体系，总共才8种情绪呀
ps: 我也是scut的！大佬你是哪一届的呀,求认识

**Comment by xwzhong** [comment]
@ccy961226 
hi, 
    同学你好，我是16届本科毕业生，请问你是哪个研究方向的？
    关于你提到的emotion embedding，大连理工的数据是8种情感维度，论文只是用了这些数据训练分类器，训练模型的时候，先用情感分类器判别response的情感，得到情感标签，然后将这标签映射到指定维度，用来代表emotion embedding，将情感信息直接以real value输入seq2seq，维度过低会带来信息上的缺失，当然引入方式也是很重要的，不过，这里说高维确实也有失偏颇，改成指定维度会好点。

best wish！

**Comment by CCYChongyanChen** [comment]
我现在大四，打算往Affective Computing

**Comment by xwzhong** [comment]
@ccy961226  👍
