### ISSUE TITLE
Can you explain the concept "tuned" in detail ?

### ISSUE THREAD

**Issue by moonlight1776** [xwzhong/papernote#2]
Hello, xwzhong
I am confused about the concept "**tuned**" , how to use the matrix and how we can get it ?
**tuned：For adaptation, the second configuration uses an additional transformation matrix of the sentence embeddings. The matrix is parameterized using the STS training data。**
Thank you very much !

**Comment by xwzhong** [comment]
hi,
here is my opionion:
  tuned means add a maxtric calculation after encode the sentence embedding( something like feedforward operation), that convert vector u(or v) to u*(or v*), then use formula 2 get similarity between u* and v*. using STS training data, we can optimize the matrix.
  for the reason why the author do that, i guess, he want fit the STS similary  degree ranging from 0 to 5. if we just use formula 2, it just a liner transformation, but the truth may be not, so, maybe that is why the author add the transformation matrix, for fitting the STS data itself.
